apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: chywiz/e-app-backend:03dfb9d660e02bd4a2516b26a9aef810f869a5ba

          ports:
            - containerPort: 5000

          envFrom:
            - secretRef:
                name: backend-env
