services:

  backend:
    image: chywiz/e-app-backend
    restart: always
    env_file: 
      - ./backend/.env.prod
    expose:
      - "5000"

  frontend:
    image: chywiz/e-app-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend