apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chywiz/e-app-frontend:62c5ceb3e94afb1e33030fe311fed2b5bffe489c
        ports:
        - containerPort: 80
