apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chywiz/e-app-frontend:03dfb9d660e02bd4a2516b26a9aef810f869a5ba
        ports:
        - containerPort: 80
