name: CI-CD Deploy to E-app into EC2

on:
  push:
    branches:
      - main



env:
  DOCKER_BACKEND: chywiz/e-app-backend
  DOCKER_FRONTEND: chywiz/e-app-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKER_BACKEND }}:latest

      - name: Build and push frontend image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKER_FRONTEND }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull latest images
        working-directory: /home/ubuntu/Proshop 
        run: docker compose pull

      - name: Restart containers
        working-directory: /home/ubuntu/Proshop 
        run: docker compose up -d

      - name: Remove old images
        run: docker image prune -f