name: CI-CD Deploy to E-app into EC2

on:
  push:
    branches:
      - main



env:
  DOCKER_BACKEND: chywiz/e-app-backend
  DOCKER_FRONTEND: chywiz/e-app-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend (ARM64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t $DOCKER_USERNAME/e-app-backend:latest \
            --push ./backend

      - name: Build & Push Frontend (ARM64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t $DOCKER_USERNAME/e-app-frontend:latest \
            --push ./frontend

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull latest images
        working-directory: /home/ubuntu/Proshop 
        run: docker compose pull

      - name: Restart containers
        working-directory: /home/ubuntu/Proshop 
        run: docker compose up -d

      - name: Remove old images
        run: docker image prune -f